"""Initial Lingvar PostgreSQL schema.

This revision is an immutable baseline.  Later model changes require a new
revision; do not edit this file to match future ORM metadata.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "nouns",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("cases_pojed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cases_mnoga", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cases_menska", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_nouns_id", "nouns", ["id"])
    op.create_index("ix_nouns_word", "nouns", ["word"])

    op.create_table(
        "pronouns",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("cases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_pronouns_id", "pronouns", ["id"])
    op.create_index("ix_pronouns_word", "pronouns", ["word"])

    op.create_table(
        "verbs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("cases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_verbs_id", "verbs", ["id"])
    op.create_index("ix_verbs_word", "verbs", ["word"])

    op.create_table(
        "numerators",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("translation", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_numerators_id", "numerators", ["id"])
    op.create_index("ix_numerators_word", "numerators", ["word"])

    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("parent_rule_id", sa.Integer(), nullable=True),
        sa.Column("ordering", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_rule_id"], ["rules.id"]),
    )
    op.create_index("ix_rules_id", "rules", ["id"])
    op.create_index("ix_rules_title", "rules", ["title"])
    op.create_index("ix_rules_parent_rule_id", "rules", ["parent_rule_id"])

    op.create_table(
        "word_test_stats",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word_type", sa.String(length=50), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_correct", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("user_id", "word_type", "word_id"),
    )
    op.create_index("ix_word_test_stats_user_id", "word_test_stats", ["user_id"])
    op.create_index("ix_word_test_stats_word_type", "word_test_stats", ["word_type"])
    op.create_index("ix_word_test_stats_word_id", "word_test_stats", ["word_id"])


def downgrade():
    raise RuntimeError(
        "Downgrade of the initial schema is forbidden: it could delete Lingvar data."
    )
